# _config.yml
theme: minima
title: "JJ’s ePortfolio"
description: "Demonstrating Proficiency in Software Design, Algorithms, and Databases"

include:
  - _pages

nav:
  - title: Software Design & Engineering
    url: /software-design
  - title: Algorithms & Data Structures
    url: /algorithms-data-structures
  - title: Databases
    url: /databases
