theme: minima        # built-in GitHub Pages theme
title: “JJ's ePortfolio”
description: “Demonstrating Proficiency in Software Design, Algorithms, and Databases”
include:
  - _pages


nav:
  - title: Home
    url: /
  - title: Software Design & Engineering
    url: /software-design
  - title: Algorithms & Data Structures
    url: /algorithms-data-structures
  - title: Databases
    url: /databases
